### ISSUE TITLE
install

### ISSUE THREAD

**Issue by digitalbread** [code-soup/wordpress-plugin-boilerplate#53] opened 2023-06-24 13:37 UTC
Hello, I'm glad to see this project being updated ( I used it a few years back and it was super helpful), but I can't seem to get it to install and the wiki instructions appear to be out of date. I'd be happy to help update instructions if I can get things working. Seems that a lot of the structure has changed. 
1. The wiki installation section references several files to update that don't exist anymore so that method failed.
2. The setup.sh script looks for a setup.php file which is missing and the index.php file that gets created only has the meta data in it. Also the namespace does not get updated in the directories, only the run.php file. (Maybe because I dev on windows?)
Thanks for all your work on this project and please let me know how I can help.
Russ

**Comment by Bobz-zg** [comment] 2023-06-27 04:51
@digitalbread still working on some tweaks sorry for the trouble.
I'll update with working version in a day or two. Need to test properly this time :)
I have replaced manual installation with setup script which has issues, as you mentiond. Still tweaking some bits but it's close to being done.

**Comment by digitalbread** [comment] 2023-06-27 19:00
@Bobz-zg sounds great and thank you for the update.

**Comment by Bobz-zg** [comment] 2023-07-16 05:55
https://github.com/code-soup/wordpress-plugin-boilerplate/wiki/04.-Installation

**Comment by Bobz-zg** [comment] 2023-07-17 02:31
@digitalbread would you mind giving a shot to install script and let me know if you encounter any issues.
I managed to test only on Ubuntu and MacOS, if you use Windows let me know which version and I'll check.

**Comment by digitalbread** [comment] 2023-07-17 12:28
Hey @Bobz-zg 
I run dev on Windows 11 using Laragon https://laragon.org/
Something went wrong and here is the console session.

sh setup.sh
Plugin Name (required): Test Me
Plugin URI (The home page of the plugin. Leave blank if not applicable): https://google.com
Description (A short description of the plugin. Keep this description to fewer than 140 characters.) (required): my cool plugin
Version (The current version number of the plugin) [default: 0.0.1]: 1.0.0
Requires at least (The lowest WordPress version that the plugin will work on) [default: 6.0]:
Requires PHP (The minimum required PHP version) [default: 7.4]:
Author (The name of the plugin author. Leave blank if not applicable): digitalbread
Author URI (The author’s website or profile on another website. Leave blank if not applicable): https://google.com
License (The short name (slug) of the plugin’s license (e.g. GPLv2).) [default: GPL-3.0+]:
License URI (A link to the full text of the license. Leave blank if not applicable):
Text Domain (The gettext text domain of the plugin.) (required): test-me
Enter PHP namespace (required):  TestMe
Enter Plugin Prefix (required):  test-me-
index.php setup completed.
Your local development URL where WordPress is installed [default: http://localhost]: https://dev.local
Path to WP plugins folder [default: /wp-content/plugins]:
Enter DEV_PROXY_URL [default: http://localhost]: https://dev.local
Enter DEV_PROXY_PORT [default: 8080]: 3000
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/wppb/test-me-/g: No such file or directory
sed: can't read s/WPPB/TestMe/g: No such file or directory
sed: can't read s/__PLUGIN_MIN_WP_VERSION__/6.0/g: No such file or directory
sed: can't read s/__PLUGIN_MIN_PHP_VERSION__/7.4/g: No such file or directory
sed: can't read s/__PLUGIN_MIN_MYSQL_VERSION__//g: No such file or directory
sed: can't read s/__PLUGIN_PREFIX__/test-me-/g: No such file or directory
sed: can't read s/__PLUGIN_NAME__/Test Me/g: No such file or directory
sed: can't read s/__PLUGIN_VERSION__/1.0.0/g: No such file or directory
Do you want to run git setup? (Recommended. This will remove Boilerplate history and create new clean git repository) (y/n):

Thanks for working on this let me know what I can do to help.
Russ

**Comment by Bobz-zg** [comment] 2023-07-28 09:01
@digitalbread could you test this one now please.
It works for me using PowerShell and Win 11 home

**Comment by digitalbread** [comment] 2023-07-28 13:32
Hey @Bobz-zg 
Everything appeared to work great until the final step of Yarn Build.
Possibly the variable fileName is missing?
I got this:

λ yarn build
yarn run v1.22.19
$ webpack --mode development --progress --config src/config/config.webpack.js
[webpack-cli] Error: Conflict: Multiple chunks emit assets to the same filename styles/undefined.css (chunks admin and common)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:4626:12
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:91:34
    at Array.<anonymous> (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\cache\MemoryCachePlugin.js:45:13)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:91:19
    at Hook.eval [as callAsync] (eval at create (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Cache.get (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:75:18)
    at ItemCacheFacade.get (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\CacheFacade.js:115:15)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:4572:22
    at arrayEach (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2405:9)
    at Object.each (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2846:9)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:4561:14
    at symbolIterator (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:3482:9)
    at done (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:3527:9)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2830:7
    at done (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2865:11)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2818:7
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:4666:18
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:107:20)
    at ItemCacheFacade.store (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\CacheFacade.js:141:15)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:4663:25
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:91:34
    at Array.<anonymous> (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\cache\MemoryCachePlugin.js:45:13)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:91:19
    at Hook.eval [as callAsync] (eval at create (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Cache.get (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:75:18)
    at ItemCacheFacade.get (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\CacheFacade.js:115:15)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:4572:22
    at arrayEach (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2405:9)
    at Object.each (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2846:9)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:4561:14
    at symbolIterator (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:3482:9)
    at timesSync (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2297:7)
    at Object.eachLimit (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:3463:5)
    at Compilation.createChunkAssets (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:4538:12)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:3108:14
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:3289:6
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:2818:7
    at done (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\neo-async\async.js:3522:9)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:3252:8
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:3361:32
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:107:20)
    at ItemCacheFacade.store (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\CacheFacade.js:141:15)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Compilation.js:3361:11
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:91:34
    at Array.<anonymous> (C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\cache\MemoryCachePlugin.js:45:13)
    at C:\laragon\www\dev\wp-content\plugins\test-plugin\node_modules\webpack\lib\Cache.js:91:19
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by digitalbread** [comment] 2023-07-28 15:22
Also, I got the same resulting error whether I used PowerShell or Cmdr Terminal.

**Comment by Bobz-zg** [comment] 2023-07-29 06:42
Oh, what you say is correct - fileName was missing.
Fixed now with few other things. Hopefully should be good, could you check now please?

**Comment by digitalbread** [comment] 2023-07-29 16:28
Hey @Bobz-zg 
Ok I made it through all the steps in the installation instructions using the following params in the setup.sh process

λ sh setup.sh
Plugin Name (required): Test Plugin
Plugin URI (The home page of the plugin. Leave blank if not applicable): https://google.com
Description (A short description of the plugin. Keep this description to fewer than 140 characters.) (required): this is a cool test plugin
Version (The current version number of the plugin) [default: 0.0.1]:
Requires at least (The lowest WordPress version that the plugin will work on) [default: 6.0]:
Requires PHP (The minimum required PHP version) [default: 7.4]:
Author (The name of the plugin author. Leave blank if not applicable): russmc
Author URI (The author’s website or profile on another website. Leave blank if not applicable): https://google.com
License (The short name (slug) of the plugin’s license (e.g. GPLv2).) [default: GPL-3.0+]:
License URI (A link to the full text of the license. Leave blank if not applicable):
Text Domain (The gettext text domain of the plugin.) (required): test-plugin
Enter PHP namespace (required):  testPlugin
Enter Plugin Prefix (required):  test_plugin_
index.php setup completed.
Your local development URL where WordPress is installed [default: http://localhost]:
Path to WP plugins folder [default: /wp-content/plugins]:
Enter DEV_PROXY_URL [default: http://localhost]:
Enter DEV_PROXY_PORT [default: 8080]:
Updating files. Please wait
Do you want to run git setup? (Recommended. This will remove Boilerplate history and create new clean git repository) (y/n): y

I ran "composer install", "yarn" and "yarn build" with no errors. I then tried to run "yarn dev" to begin dev with hot loading at the proxy url and got the following:

λ yarn dev
yarn run v1.22.19
$ webpack serve --hot --mode development --color --config src/config/config.webpack.js
[webpack-cli] Failed to load 'C:\laragon\www\dev\wp-content\plugins\test-plugin\src\config\config.webpack.js' config
[webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Url.parse (node:url:183:3)
    at Object.urlParse [as parse] (node:url:154:13)
    at Object.<anonymous> (C:\laragon\www\dev\wp-content\plugins\test-plugin\src\config\webpack\config.watch.js:7:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Since that didn't work, I went directly to my dev.local/wp-admin install, logged in and tried to activate the test-plugin and got the following:

Plugin could not be activated because it triggered a fatal error.
Fatal error: Uncaught Error: Class "estPlugin\Activator" not found in C:\laragon\www\dev\wp-content\plugins\test-plugin\index.php:21 Stack trace: #0 C:\laragon\www\dev\wp-includes\class-wp-hook.php(308): {closure}('') #1 C:\laragon\www\dev\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #2 C:\laragon\www\dev\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #3 C:\laragon\www\dev\wp-admin\plugins.php(194): do_action('activate_test-p...') #4 {main} thrown in C:\laragon\www\dev\wp-content\plugins\test-plugin\index.php on line 21

Looks like the "t" is missing from the PHP namespace entered in the setup.sh process.

Getting closer.
Thanks for your work on this.
Russ

**Comment by digitalbread** [comment] 2023-07-29 16:36
It looks like the PHP Namespace is only wrong in the index.php files in plugin root 

register_activation_hook( __FILE__, function() {

    // On activate do this
    	estPlugin\Activator::activate();
});

register_deactivation_hook( __FILE__, function () {
    
    // On deactivate do that
    	estPlugin\Deactivator::deactivate();
});

But it looks correct in the top of the files the script edited.

test-plugin/includes/class-init.php top of the file is "namespace testPlugin;"

I manually edited index.php adding the missing "t" and the plugin did activate.

Weird!

Oh, and 1 more thing in the generated index.php file. The line for Author uri looks like this,
 * Author URI: 
 https:///google.com[D[D[D[D[D[D[D[D[D[D[D[3~[F[D[D[D[B[F[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[B[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[[[C[C[C[C[C[C[C[C/google.com
 
each little "?" says ESC in it, but that didn't paste over in my comment.
Thanks again,
Russ

**Comment by Bobz-zg** [comment] 2023-08-02 08:25
@digitalbread  Could you run another test please.
I was not able to reproduce author UI problem, do you recall which URL you used by any chance?
It's most likely some special char which I need to escape.

**Comment by digitalbread** [comment] 2023-08-02 21:58
@Bobz-zg I figured out the issue with the strange characters. It is due to when a user mistypes a string and corrects it in the terminal. I updated these 2 files that solved the issue mainly adding user input sanitization and debug output. I also changed the questions to YELLOW and debug to RED as the RED was much harder to read.

This file has the most changes.
setup/prompt-header.sh

```
#!/bin/bash

# Set color variables for text formatting
YELLOW='\033[1;33m' # Yellow color
RED='\033[0;31m'    # Red color
GREEN='\033[0;32m'  # Green color
NC='\033[0m'       # No color

# Prompt the user to enter Plugin Name (required)
read -rp "$(echo -e "${YELLOW}Plugin Name (required):${NC} ")" plugin_name
while [[ -z "$plugin_name" ]]; do
    read -rp "$(echo -e "${YELLOW}Plugin Name (required):${NC} ")" plugin_name
done
plugin_name=$(echo "$plugin_name" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Plugin Name is [$plugin_name]${NC}"
# Prompt the user to enter Plugin URI (optional)
read -rp "Plugin URI (The home page of the plugin. Leave blank if not applicable): " plugin_uri
plugin_uri=$(echo "$plugin_uri" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Plugin URI is [$plugin_uri]${NC}"
# Prompt the user to enter Description (required)
read -rp "$(echo -e "${YELLOW}Description (A short description of the plugin. Keep this description to fewer than 140 characters.) (required):${NC} ")" plugin_description
plugin_description=$(echo "$plugin_description" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Plugin Descritpion is [$plugin_description]${NC}"
while [[ -z "$plugin_description" ]]; do
    read -rp "$(echo -e "${YELLOW}Description (A short description of the plugin. Keep this description to fewer than 140 characters.) (required):${NC} ")" plugin_description
	plugin_description=$(echo "$plugin_description" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
	echo -e "${RED}Debug: Plugin Descritpion is [$plugin_description]${NC}"
done

# Prompt the user to enter Version with a default value of 0.0.1
read -rp "$(echo -e "${GREEN}Version (The current version number of the plugin) [default: 0.0.1]:${NC} ")" plugin_version
plugin_version=${plugin_version:-0.0.1}
plugin_version=$(echo "$plugin_version" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Plugin Version is [$plugin_version]${NC}"
# Prompt the user to enter Requires at least with a default value of 6.0
read -rp "$(echo -e "${GREEN}Requires at least (The lowest WordPress version that the plugin will work on) [default: 6.0]:${NC} ")" requires_wordpress
requires_wordpress=${requires_wordpress:-6.0}
requires_wordpress=$(echo "$requires_wordpress" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Requires Wordpress is [$requires_wordpress]${NC}"
# Prompt the user to enter Requires PHP with a default value of 7.4
read -rp "$(echo -e "${GREEN}Requires PHP (The minimum required PHP version) [default: 7.4]:${NC} ")" requires_php
requires_php=${requires_php:-7.4}
requires_php=$(echo "$requires_php" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Requires PHP is [$requires_php]${NC}"
# Prompt the user to enter Author (optional)
read -rp "Author (The name of the plugin author. Leave blank if not applicable): " plugin_author
plugin_author=$(echo "$plugin_author" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Requires PHP is [$plugin_author]${NC}"
# Prompt the user to enter Author URI (optional)
read -rp "Author URI (The author’s website or profile on another website. Leave blank if not applicable): " plugin_author_uri
plugin_author_uri=$(echo "$plugin_author_uri" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Plugin Author URI is [$plugin_author_uri]${NC}"
# Prompt the user to enter License with a default value of GPL-3.0+
read -rp "$(echo -e "${GREEN}License (The short name (slug) of the plugin’s license (e.g. GPLv2).) [default: GPL-3.0+]:${NC} ")" plugin_license
plugin_license=${plugin_license:-GPL-3.0+}
plugin_license=$(echo "$plugin_license" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Plugin License is [$plugin_license]${NC}"
# Prompt the user to enter License URI (optional)
read -rp "License URI (A link to the full text of the license. Leave blank if not applicable): " license_uri
license_uri=$(echo "$license_uri" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: License URI is [$license_uri]${NC}"
# Prompt the user to enter Text Domain (required)
read -rp "$(echo -e "${YELLOW}Text Domain (The gettext text domain of the plugin.) (required):${NC} ")" plugin_textdomain
plugin_textdomain=$(echo "$plugin_textdomain" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
echo -e "${RED}Debug: Plugin Text Domain is [$plugin_textdomain]${NC}"
while [[ -z "$plugin_textdomain" ]]; do
    read -rp "$(echo -e "${YELLOW}Text Domain (The gettext text domain of the plugin.) (required):${NC} ")" plugin_textdomain
	plugin_textdomain=$(echo "$plugin_textdomain" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")  # Sanitize user input
	echo -e "${RED}Debug: Plugin Text Domain is [$plugin_textdomain]${NC}"
done
# Prompt the user for input to replace WPPB with PHP namespace
read -rp "$(echo -e "${YELLOW}Enter PHP namespace (required): ${NC} ")" php_namespace
php_namespace=$(printf '%q\n' "$php_namespace")
echo -e "${RED}Debug: PHP namespace is [$php_namespace]${NC}"
while [[ -z "$php_namespace" ]]; do
    read -rp "$(echo -e "${YELLOW}Enter PHP namespace (required): ${NC} ")" php_namespace
	php_namespace=$(printf '%q\n' "$php_namespace")
	echo -e "${RED}Debug: PHP namespace is [$php_namespace]${NC}"
done
# Prompt the user for input plugin prefix
read -rp "$(echo -e "${YELLOW}Enter Plugin Prefix (required): ${NC} ")" plugin_prefix
plugin_prefix=$(printf '%q\n' "$plugin_prefix")
echo -e "${RED}Debug: PHP Prefix is [$plugin_prefix]${NC}"
while [[ -z "$plugin_prefix" ]]; do
    read -rp "$(echo -e "${YELLOW}Enter Plugin Prefix (required): ${NC} ")" plugin_prefix
	plugin_prefix=$(printf '%q\n' "$plugin_prefix")
	echo -e "${RED}Debug: PHP Prefix is [$plugin_prefix]${NC}"
done

```
Then setup/setup-index.sh only changed 2 lines replacing 
`
${php_namespace} 
`
with 
`
\\$php_namespace  
`
which fixed the missing character in the index.php file.

Here's the content of the entire file.
```
#!/bin/bash

# Delete index.php file if it exists
if [[ -f "index.php" ]]; then
  rm index.php
fi

header_content="<?php

defined('WPINC') || die;

/**
 * Plugin Name: $plugin_name"

if [[ -n "$plugin_uri" ]]; then
    header_content+="\n * Plugin URI: $plugin_uri"
fi

header_content+="\n * Description: $plugin_description
 * Version: $plugin_version
 * Requires at least: $requires_wordpress
 * Requires PHP: $requires_php"

if [[ -n "$plugin_author" ]]; then
    header_content+="\n * Author: $plugin_author"
fi

if [[ -n "$plugin_author_uri" ]]; then
    header_content+="\n * Author URI: $plugin_author_uri"
fi

header_content+="\n * License: $plugin_license"

if [[ -n "$license_uri" ]]; then
    header_content+="\n * License URI: $license_uri"
fi

header_content+="\n * Text Domain: $plugin_textdomain
 */"

printf "%b" "$header_content" > index.php

# NOTE: Activation hooks need to be inside index.php file or it might not work properly
# It can fail without error, WordPress is silently failing in case of error

# The code that runs during plugin activation.
# - includes/Activator.php
activation_hook_content="\n
register_activation_hook( __FILE__, function() {

    // On activate do this
    \\$php_namespace\Activator::activate();
});"

printf "%b" "$activation_hook_content" >> index.php

# The code that runs during plugin deactivation.
# - includes/Deactivator.php
deactivation_hook_content="\n
register_deactivation_hook( __FILE__, function () {
    
    // On deactivate do that
    \\$php_namespace\Deactivator::deactivate();
});"

printf "%b" "$deactivation_hook_content" >> index.php

# Run plugin, run
run_content="\n
include \"run.php\";"

printf "%b" "$run_content" >> index.php

echo "index.php setup completed."
```

**Comment by digitalbread** [comment] 2023-08-02 22:29
One last thing.
Using Laragon, I develop with https:// activated and working. I do this in my current boilerplate, which is the old one from this repo, I've implemented Laravel Mix which is an elegant wrapper for webpack. I was wondering if you'd consider implementing Laravel Mix and the use of ssl/https?

I started down the path of making your webpack implementation work with https but thought before I continue I'd ask your opinion on switching to Laravel Mix. 

In the case for hot loading and locahost proxy you could prompt the user for https or http, if https is chosen ask for the path for .crt and .key to include on the webpack.mix.js. 

I will include a copy of mine here. I do like however your implementation of scss and the dist folder producing unique postfix id's on the generated files. 

Just something to think about. I think you'd like Laravel Mix. I also have it so the production command produces a usable .zip archive of the plugin for distribution.

Here's an example of one I'm using now.  plugin root > webpack.mix.js

```
/** @format */

const { readFileSync, existsSync, mkdirSync, rmdirSync } = require("fs");
const { copySync } = require("fs-extra");
const { zip } = require("zip-a-folder");
const mix = require("laravel-mix");
const { join } = require("path");
const os = require("os");

require("mix-env-file");

// set env file
if (existsSync(join(__dirname, ".env"))) {
    mix.env(join(__dirname, ".env"));

    console.log("Env file loaded");
}

// plugin directory name
const pluginDirName = __dirname
    .replace(/(\/|\\)+/g, "/")
    .split("/")
    .pop();

mix
// scss files
    .sass(join("src", "scss", "main.scss"), join("css"))
    .sass(join("src", "scss", "admin.scss"), join("css"))

    // js files
    .js(join("src", "js", "main.js"), join("js"))
    .js(join("src", "js", "admin.js"), join("js"))

    .react()

    // create websocket server for hot reload
    .browserSync({
        proxy: "https://dev.local",
        files: [
            "assets/css/*.css",
            "assets/js/*.js",
            "assets/imgs/*",
        ],
        https: {
            key: "C:/laragon/etc/ssl/laragon.key",
            cert: "C:/laragon/etc/ssl/laragon.crt",
        },
        ghostMode: false,
        watch: true,
        open: true,
    })

    // set where assets will be exported
    .setResourceRoot(join("/", "wp-content", "assets", pluginDirName, "assets"))

    // set public path
    .setPublicPath(join("assets"))

    // save files from cache
    .webpackConfig({
        cache: {
            type: "filesystem",
        },
    })

    // zip the plugin after build is done
    .after(async (webpackStats) => {
        if (mix.inProduction()) {
            const pkg = readFileSync(join(__dirname, "package.json"), "utf8");
            const json = JSON.parse(pkg);
            const dirName = join(os.tmpdir(), json.name);

            try {
                if (existsSync(dirName)) {
                    rmdirSync(dirName, { recursive: true });
                }

                mkdirSync(dirName);

                const files = [
                    // directories
                    "assets",
                    "includes",
                    "languages",
                    "lib",
                    "plugin",
                    "vendor",
                    // files
                    "LICENSE.txt",
                    "README.md",
                    "share-portal-pro.php",
                    "uninstall.php",

                ];

                files.forEach((dir) => {
                    if (existsSync(join(__dirname, dir))) {
                        copySync(join(__dirname, dir), join(dirName, dir));
                    }
                });

                await zip(dirName, join(__dirname, json.name + ".zip"));
            } catch (e) {
                console.log("Failed to pack the plugin");
            }

            rmdirSync(dirName, { recursive: true });
        }
    });
```
Here's a copy of the package.json file

```
{
  "name": "test-plugin",
  "version": "0.0.1",
  "description": "test plugin description",
  "main": "index.js",
  "scripts": {
    "generate-mo": "bash generate-mo-files.sh",
    "generate-po": "bash generate-po-files.sh --domain plugin-text-domain --languages fr_FR,en_US,ar_AR",
    "watch": "npx mix watch",
    "build": "npx mix --production"
  },
  "author": "digibread",
  "author_email": "",
  "license": "GPL-3.0-or-later",
  "devDependencies": {
    "@babel/preset-react": "^7.22.5",
    "@types/jquery": "^3.5.16",
    "browser-sync": "^2.27.10",
    "browser-sync-webpack-plugin": "^2.3.0",
    "laravel-mix": "^6.0.49",
    "mix-env-file": "^0.1.1",
    "resolve-url-loader": "^5.0.0",
    "sass": "^1.56.2",
    "sass-loader": "^12.1.0",
    "zip-a-folder": "^1.1.5"
  },
  "dependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@fontsource/roboto": "^5.0.3",
    "@mui/icons-material": "^5.11.16",
    "@mui/lab": "^5.0.0-alpha.133",
    "@mui/material": "^5.13.4",
    "@reduxjs/toolkit": "^1.9.5",
    "bootstrap": "^5.2.2",
    "clipboard": "^2.0.6",
    "flatpickr": "^4.6.13",
    "inputmask": "^5.0.8",
    "just-validate": "^4.2.0",
    "purecss": "^3.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^8.0.7",
    "sweetalert2": "^11.7.12",
    "datatables.net-dt": "^1.13.5",
    "datatables.net-autofill-dt": "^2.6.0",
    "datatables.net-buttons-dt": "^2.4.1",
    "datatables.net-responsive-dt": "^2.5.0"
  }
}
```

The commands are simple after composer install, I run

`
npm i
`

then

`
npm run watch
`

and finally to create a plugin-slug.zip archive for distribution

`
npm run build
`
Let me know what you think and again thanks for all your hard work on this project.
Russ

**Comment by Bobz-zg** [comment] 2023-08-06 06:25
Hi @digitalbread thanks for detailed update and continuous support.
Would you be willing to make a PR with proposed changes?

Personally I don't use Laravel Mix, but I'm ok having it as an option.

**Closed as completed** 2023-09-24 11:35 UTC
